"""
Report Generator
"""
import json
from typing import Callable
from core.ai import AIClient
from .prompts import REPORT_GENERATION_PROMPT

class ReportGenerator:
    def __init__(self, notify: Callable[[str], None]):
        self.notify = notify

    def generate(self, question: str, objectives: list[str], analyses: list[dict]) -> str:
        """生成研究报告"""
        self.notify("📝 正在生成研究报告...")
        
        relevant_analyses = [
            a for a in analyses 
            if a.get("success") and a.get("data", {}).get("relevant", True)
        ]
        
        if not relevant_analyses:
            return "❌ 没有找到相关论文，无法生成报告。"
        
        analyses_text = self._format_analyses(relevant_analyses)
        short_title = (question[:30] + "...") if len(question) > 30 else question
        
        prompt = REPORT_GENERATION_PROMPT.format(
            question=question,
            objectives="\n".join([f"- {o}" for o in objectives]),
            paper_count=len(relevant_analyses),
            analyses=analyses_text,
            short_title=short_title
        )
        
        from core.ai import get_ai_client
        ai = get_ai_client()
        result = ai.call(prompt, json_mode=False)
        
        if result.success:
            return result.data.get("text", "")
        return f"❌ 报告生成失败: {result.error}"

    def _format_analyses(self, analyses: list[dict]) -> str:
        text = ""
        for i, a in enumerate(analyses[:20], 1):
            data = a.get("data", {}).get("analysis", {})
            if not data: # Fallback for old or raw format
                 data = a.get("data", {})
                 
            text += f"\n## 论文 {i} (DOI: {a.get('doi', 'N/A')})\n"
            text += f"- 研究目的: {data.get('research_purpose', 'N/A')}\n"
            text += f"- 材料/体系: {data.get('material_system', 'N/A')}\n"
            text += f"- 关键方法: {data.get('key_methods', 'N/A')}\n"
            text += f"- 核心结果: \n{data.get('core_results_table', 'N/A')}\n"
            text += f"- 结论: {data.get('author_conclusion', 'N/A')}\n"
            text += f"- 不足: {data.get('limitations', 'N/A')}\n"
        return text

# --- Phase A-4: Executor "State-Only" Interface ---
from .types import ResearchState
import logging
logger = logging.getLogger('deep_research')

def report(state: ResearchState) -> str:
    """
    [New] 纯状态驱动的报告生成逻辑
    输入: state.evidence, state.intermediate_results["synthesis"]
    输出: Report String
    """
    def temp_notify(msg):
        logger.info(msg)
        
    # If final report already generated by synthesizer, just return/refine it?
    if state.final_report and "synthesis" in state.intermediate_results:
        # User might want to run ReportGenerator separately or just use Synthesis output
        # Synthesizer returns "synthesis_text" which is Markdown.
        # ReportGenerator generates text from "analyses" (which implies deep analysis per paper?)
        # Our State.Evidence list is close to "analyses" needed by ReportGenerator.
        # Let's try to use ReportGenerator if final_report is empty, or as an alternative.
        return state.final_report # Return existing if synthesis did it.
        
    # If not, try to generate using ReportGenerator
    # But ReportGenerator expects 'analyses' list wrapped in a specific way.
    # Our 'state.evidence' is [Dict].
    # Need to map evidence to expected format.
    
    gen = ReportGenerator(temp_notify)
    
    # Map evidence to ReportGenerator 'analyses' format
    # evidence item: { "title":..., "implementation":..., ...}
    # ReportGenerator expects: { "data": { "analysis": ... } } or just data.
    analyses_input = []
    for ev in state.evidence:
        analyses_input.append({
            "doi": ev.get("doi"),
            "data": {
                "relevant": True,
                "analysis": {
                    "research_purpose": ev.get("title"), # fallback
                    "material_system": ev.get("topic"), # fallback
                    "key_methods": ev.get("implementation"),
                    "core_results_table": ev.get("performance_results"),
                    "author_conclusion": ev.get("summary"),
                    "limitations": ev.get("limitations")
                }
            }
        })
        
    objectives = state.plan.objectives if state.plan else []
    
    text = gen.generate(state.question.question, objectives, analyses_input)
    return text
